# Version of docker-compose
version: '3'

services:
  phoenix-blog:
    image: registry.bitsofether.com/phoenix-blog:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
          HOST: $HOST
          PORT: $PORT
          MIX_ENV: prod
          SECRET_KEY_BASE: $SECRET_KEY_BASE
          SMTP_EMAIL: $SMTP_EMAIL
          SMTP_USERNAME: $SMTP_USERNAME
          SMTP_PASSWORD: $SMTP_PASSWORD
          GITHUB_HANDLE: $GITHUB_HANDLE
          GITHUB_USERNAME: $GITHUB_USERNAME
          GITHUB_PAT: $GITHUB_PAT
          ERL_CRASH_DUMP: $ERL_CRASH_DUMP
    ports:
      - "$PORT:$PORT"
    volumes:
      - /var/log:/opt/log
